USE rtci-testing
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE dbo.updateAsset
	@AssetUID int =NULL,
	@ModeCode nvarchar(3) =NULL,
	@NTDModeCode nchar(2) =NULL,
	@AssetDesc nvarchar(500) =NULL,
	@AgencyDetail nvarchar(500) =NULL,
	@AssetStatus varchar(3) =NULL,
	@AssetType numeric(18, 6) =NULL,
	@YRBuilt smallint =NULL,
	@YRInService date =NULL,
	@AgencyUsefulLife int =NULL,
	@StdUsefulLife int =NULL,
	@Quantity float =NULL,
	@UnitType varchar(20) =NULL,
	@UpdateType nvarchar(100) =NULL,
	@UnitCost money =NULL,
	@AgencySoftCost float =NULL,
	@TotalCost money =NULL,
	@YRCost smallint =NULL,
	@AssetPhysAddress nvarchar(255) =NULL,
	@AssetPhysZIP nchar(5) =NULL,
	@Latitude numeric(15, 10) =NULL,
	@Longitude numeric(15, 10) =NULL,
	@LineDivision nvarchar(50) =NULL,
	@BranchGarage nvarchar(50) =NULL,
	@SegmentRoute nvarchar(50) =NULL,
	@LocLinearStart nvarchar(50) =NULL,
	@LocLinearEnd nvarchar(50) =NULL,
	@AgencyAssetUID nvarchar(50) =NULL,
	@AgencyAssetClass nvarchar(50) =NULL,
	@AgencyDeptOwner nvarchar(255) =NULL,
	@AgencyNotes nvarchar(4000) =NULL,
	@AgencyConditionRating numeric(2, 1) =NULL,
	@AgencyParentUID nvarchar(50) =NULL,
	@AgencyProjNum nvarchar(50) =NULL,
	@AgencyProjCat nvarchar(50) =NULL,
	@AgencyProjDesc nvarchar(255) =NULL,
	@AgencySubFleetID nvarchar(50) =NULL,
	@TOS char(2) =NULL,
	@RevenueFlag bit =NULL,
	@PriorityStatus tinyint =NULL,
	@TCPScore tinyint =NULL,
	@SquareFootage numeric(18, 2) =NULL,
	@HistoricPresrvFlag bit =NULL,
	@ItemizedFlag bit =NULL,
	@Manufacturer nvarchar(50) =NULL,
	@ManufacturerCode nchar(3) =NULL,
	@ModelNumber nvarchar(50) =NULL,
	@FuelType char(2) =NULL,
	@CapacitySeated smallint =NULL,
	@CapacityStanding smallint =NULL,
	@DataYR smallint =NULL,
	@DataSRC varchar(50) =NULL,
	@RTCICycle char(5) =NULL,
	@ReviewFlag bit =NULL,
	@ApprovedFlag bit =NULL,
	@ApprovalComment nvarchar(4000) =NULL,
	@DelayReplaceAge int =NULL,
	@Rehabed bit =NULL,
	@RehabedDate date =NULL,
	@CostNotes nvarchar(max) =NULL,
	@UserField1 nvarchar(max) =NULL,
	@UserField2 nvarchar(max) =NULL,
	@UserField3 nvarchar(max) =NULL,
	@UserField4 nvarchar(max) =NULL

    AS
    BEGIN

    UPDATE rtci_app.RTCIAssetInventory
    SET
    ModeCode = @ModeCode,
      NTDModeCode = @NTDModeCode,
      AssetDesc = @AssetDesc,
      AgencyDetail = @AgencyDetail,
      AssetStatus = @AssetStatus,
      AssetType = @AssetType,
      YRBuilt = @YRBuilt,
      YRInService = @YRInService,
      AgencyUsefulLife = @AgencyUsefulLife,
      StdUsefulLife = @StdUsefulLife,
      Quantity = @Quantity,
      UnitType = @UnitType,
      UpdateType = @UpdateType,
      UnitCost = @UnitCost,
      AgencySoftCost = @AgencySoftCost,
      TotalCost = @TotalCost,
      YRCost = @YRCost,
      AssetPhysAddress = @AssetPhysAddress,
      AssetPhysZIP = @AssetPhysZIP,
      Latitude = @Latitude,
      Longitude = @Longitude,
      LineDivision = @LineDivision,
      BranchGarage = @BranchGarage,
      SegmentRoute = @SegmentRoute,
      LocLinearStart = @LocLinearStart,
      LocLinearEnd = @LocLinearEnd,
      AgencyAssetUID = @AgencyAssetUID,
      AgencyAssetClass = @AgencyAssetClass,
      AgencyDeptOwner = @AgencyDeptOwner,
      AgencyNotes = @AgencyNotes,
      AgencyConditionRating = @AgencyConditionRating,
      AgencyParentUID = @AgencyParentUID,
      AgencyProjNum = @AgencyProjNum,
      AgencyProjCat = @AgencyProjCat,
      AgencyProjDesc = @AgencyProjDesc,
      AgencySubFleetID = @AgencySubFleetID,
      TOS = @TOS,
      RevenueFlag = @RevenueFlag,
      PriorityStatus = @PriorityStatus,
      TCPScore = @TCPScore,
      SquareFootage = @SquareFootage,
      HistoricPresrvFlag = @HistoricPresrvFlag,
      ItemizedFlag = @ItemizedFlag,
      Manufacturer = @Manufacturer,
      ManufacturerCode = @ManufacturerCode,
      ModelNumber = @ModelNumber,
      FuelType = @FuelType,
      CapacitySeated = @CapacitySeated,
      CapacityStanding = @CapacityStanding,
      DataYR = @DataYR,
      DataSRC = @DataSRC,
      RTCICycle = @RTCICycle,
      ReviewFlag = @ReviewFlag,
      ApprovedFlag = @ApprovedFlag,
      ApprovalComment = @ApprovalComment,
      DelayReplaceAge = @DelayReplaceAge,
      Rehabed = @Rehabed,
      RehabedDate = @RehabedDate,
      CostNotes = @CostNotes,
      UserField1 = @UserField1,
      UserField2 = @UserField2,
      UserField3 = @UserField3,
      UserField4 = @UserField4

      WHERE

      AssetUID = @AssetUID

     END